{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.vserg",
    "module": "logging-starter",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 9846,
          "sha512": "586f33483ed0add44b5a79b840d4aa98dc5b755886c29ccded70ad1c37b7246d4a61de47fb44871c6f0632cbfcdba43d80f3a90f09003535b4cac496599c4609",
          "sha256": "02392956ece72c78e237e156799ba30d78afa1cbf1d3a13cb7b26d1d3977802c",
          "sha1": "6ae8c371f0106fb58e24aef4fe73f9df5abcee23",
          "md5": "ac132581cb9fb519de49ccd5ec67e42d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 9846,
          "sha512": "586f33483ed0add44b5a79b840d4aa98dc5b755886c29ccded70ad1c37b7246d4a61de47fb44871c6f0632cbfcdba43d80f3a90f09003535b4cac496599c4609",
          "sha256": "02392956ece72c78e237e156799ba30d78afa1cbf1d3a13cb7b26d1d3977802c",
          "sha1": "6ae8c371f0106fb58e24aef4fe73f9df5abcee23",
          "md5": "ac132581cb9fb519de49ccd5ec67e42d"
        }
      ]
    }
  ]
}
