{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.vserg",
    "module": "logging-starter",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1347,
          "sha512": "c6d589f76877784c3133b999b8bc65f6acb298b8cb1a450366ae57eb7c136668eaae1b9b9198df1a6b6396567855f62bdb3a072b6b9dea4f9466daa98b045f30",
          "sha256": "3bc95c5eaf4e6bbac489293f5341c034566fe6484f1f33dc9ecbfd83645c830b",
          "sha1": "a0a440a565b2b4c4edc0f6ce4f951653f9391004",
          "md5": "63f72ad8637b9aaab7cbf3f8319c54cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1347,
          "sha512": "c6d589f76877784c3133b999b8bc65f6acb298b8cb1a450366ae57eb7c136668eaae1b9b9198df1a6b6396567855f62bdb3a072b6b9dea4f9466daa98b045f30",
          "sha256": "3bc95c5eaf4e6bbac489293f5341c034566fe6484f1f33dc9ecbfd83645c830b",
          "sha1": "a0a440a565b2b4c4edc0f6ce4f951653f9391004",
          "md5": "63f72ad8637b9aaab7cbf3f8319c54cd"
        }
      ]
    }
  ]
}
