{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.vserg",
    "module": "logging-starter",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1182,
          "sha512": "9ec4573691aed6a2de0c7b5bdd16b213622a128bdea8161a54e0f018550e85dec88d250798b7f176f1f1f3a89fc7dd2524fee23340e5267b631f29187ef07918",
          "sha256": "f5528c39d46cbb4b7210c8788abef7c45dfb294084f6c9e988f2814d27e6da94",
          "sha1": "e1e65f3b81a57ed707d61b33f1477d732b398be2",
          "md5": "76bd683af6f28ba0b4c51600881861a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1182,
          "sha512": "9ec4573691aed6a2de0c7b5bdd16b213622a128bdea8161a54e0f018550e85dec88d250798b7f176f1f1f3a89fc7dd2524fee23340e5267b631f29187ef07918",
          "sha256": "f5528c39d46cbb4b7210c8788abef7c45dfb294084f6c9e988f2814d27e6da94",
          "sha1": "e1e65f3b81a57ed707d61b33f1477d732b398be2",
          "md5": "76bd683af6f28ba0b4c51600881861a7"
        }
      ]
    }
  ]
}
