{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.vserg",
    "module": "logging-starter",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1353,
          "sha512": "506b1354d487b1fd4402a2fb0da65128da71362cf813c50dddf3232e3f5c214c7a3f3042c2fbac484e238ea0e98340f8d0a3d03d414fdb847550a0356e8f9efb",
          "sha256": "9ab9d832d7edd789d1b2cf7c7940bb06113a8449b35197939dd4541256f86ffd",
          "sha1": "da4f8666e1252fd8a6ed0286964bf27575dc2130",
          "md5": "7b4159f2da7d2c9e30be3a2c590c8b84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1353,
          "sha512": "506b1354d487b1fd4402a2fb0da65128da71362cf813c50dddf3232e3f5c214c7a3f3042c2fbac484e238ea0e98340f8d0a3d03d414fdb847550a0356e8f9efb",
          "sha256": "9ab9d832d7edd789d1b2cf7c7940bb06113a8449b35197939dd4541256f86ffd",
          "sha1": "da4f8666e1252fd8a6ed0286964bf27575dc2130",
          "md5": "7b4159f2da7d2c9e30be3a2c590c8b84"
        }
      ]
    }
  ]
}
