{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.vserg",
    "module": "logging-starter",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1353,
          "sha512": "d461f11379bdf5f9a3e8157472671fe91504d259ac21cb785e158b2421d7ab910de8957a17c8121f8a29b77650f568b1023cee4896ad0cf24345e7a8b566aabd",
          "sha256": "01c5b1d3f09b5169aafece7a296a1c770d083c6791b839e22785dacac22ac0d9",
          "sha1": "150aa0154bf8fd111df5b350f5e06f01439d28ec",
          "md5": "8f1eaa7286167b84d37841bc4279f8b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1353,
          "sha512": "d461f11379bdf5f9a3e8157472671fe91504d259ac21cb785e158b2421d7ab910de8957a17c8121f8a29b77650f568b1023cee4896ad0cf24345e7a8b566aabd",
          "sha256": "01c5b1d3f09b5169aafece7a296a1c770d083c6791b839e22785dacac22ac0d9",
          "sha1": "150aa0154bf8fd111df5b350f5e06f01439d28ec",
          "md5": "8f1eaa7286167b84d37841bc4279f8b7"
        }
      ]
    }
  ]
}
